from enum import Enum


class ObjectSchema(str, Enum):
    TEXT = "TEXT"
    TODO_JSON_V1 = "TODO_JSON_V1"
    ENUM_JSON_V1 = "ENUM_JSON_V1"
    TIMELINE_NOTE_JSON_V1 = "TIMELINE_NOTE_JSON_V1"
    ASSIGNMENT_RECORD_JSON_V1 = "ASSIGNMENT_RECORD_JSON_V1"
    TEXT_ISO_DATE = "TEXT_ISO_DATE"
    WEMWBS_JSON_V1 = "WEMWBS_JSON_V1"
    FILE = "FILE"
    RFC822 = "RFC822"
    IMAGE = "IMAGE"
    MESSAGE_JSON_V1 = "MESSAGE_JSON_V1"
